# Generated by Django 5.1.1 on 2024-10-03 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        ("students", "0014_alter_student_payment_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_title", models.CharField(max_length=200)),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("1", "First Semester"),
                            ("2", "Second Semester"),
                            ("3", "Third Semester"),
                            ("4", "Fourth Semester"),
                            ("5", "Fifth Semester"),
                            ("6", "Sixth Semester"),
                            ("7", "Seventh Semester"),
                            ("8", "Eighth Semester"),
                        ],
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_marks", models.IntegerField(default=100)),
                ("theory_marks", models.IntegerField(default=20)),
                ("practical_marks", models.IntegerField(default=80)),
                ("marks_obtained", models.IntegerField(default=0)),
                ("remarks", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.modules",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_obtained_marks", models.IntegerField(default=0)),
                ("percentage", models.FloatField(default=0.0)),
                ("total_marks", models.IntegerField(default=100)),
                ("theory_marks", models.IntegerField(default=20)),
                ("practical_marks", models.IntegerField(default=80)),
                ("marks_obtained", models.IntegerField(default=0)),
                ("remarks", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.exam"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.modules",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                ("subjects", models.ManyToManyField(to="exam.subject")),
            ],
        ),
    ]
