# Generated by Django 5.1.1 on 2024-10-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_result_marks_obtained_remove_result_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
    ]
