# Generated by Django 5.1.1 on 2024-10-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_subject_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='practical_marks',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='theory_marks',
            field=models.IntegerField(default=80),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
