# Generated by Django 5.1.1 on 2024-09-25 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        ("userauth", "0012_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("MORNING", "Morning"),
                            ("AFTERNOON", "Afternoon"),
                            ("EVENING", "Evening"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date_joined", models.DateField()),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.campus",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.department",
                    ),
                ),
                (
                    "english_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userauth.englishtest",
                    ),
                ),
                (
                    "modules",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.modules",
                    ),
                ),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userauth.personalinfo",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.program",
                    ),
                ),
            ],
        ),
    ]
