# Generated by Django 5.1.1 on 2024-09-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
        ("teacher", "0003_teacher_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="modules",
        ),
        migrations.AddField(
            model_name="teacher",
            name="modules",
            field=models.ManyToManyField(to="dashboard.modules"),
        ),
    ]
