# Generated by Django 5.1.1 on 2025-02-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_teacher_position'),
        ('userauth', '0013_alter_addressinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.ManyToManyField(blank=True, to='userauth.sections'),
        ),
    ]
