# Generated by Django 5.1.1 on 2025-02-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_teacher_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.CharField(choices=[('administrative', 'Administrative'), ('academic', 'Academic')], max_length=100),
        ),
    ]
