# Generated by Django 5.1.1 on 2025-02-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_alter_teacher_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('DAY', 'Day'), ('EVENING', 'Evening')], max_length=100),
        ),
    ]
