# Generated by Django 5.2 on 2025-05-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_campus_code_alter_department_code_and_more'),
        ('teacher', '0012_alter_teacher_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='program',
        ),
        migrations.AddField(
            model_name='teacher',
            name='campus',
            field=models.ManyToManyField(to='dashboard.campus'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ManyToManyField(to='dashboard.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='program',
            field=models.ManyToManyField(to='dashboard.program'),
        ),
    ]
