# Generated by Django 5.2 on 2025-05-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_campus_code_alter_department_code_and_more'),
        ('teacher', '0014_alter_teacher_department_alter_teacher_modules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='campus',
            field=models.ManyToManyField(blank=True, to='dashboard.campus'),
        ),
    ]
