# Generated by Django 5.2 on 2025-05-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_alter_teacher_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('DAY', 'Day'), ('EVENING', 'Evening')], max_length=100),
        ),
    ]
