# Generated by Django 5.1.1 on 2024-09-12 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('userauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=255, unique=True)),
                ('commencing_term', models.TextField()),
                ('date_of_admission', models.DateField()),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], max_length=50)),
                ('admission_officer', models.TextField(blank=True, null=True)),
                ('scholarship_details', models.CharField(blank=True, max_length=100, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_by', models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent/Guardian'), ('COMPANY', 'Company'), ('OTHER', 'Government/International Agency')], max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('authorize_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('annual_income', models.CharField(max_length=100)),
                ('members_in_family', models.IntegerField(default=1)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('why_us', models.CharField(choices=[('REPUTATION', 'Good brand Reputation'), ('LOCATION', 'Location'), ('COURSE', 'Course/Mode/Flexibility'), ('VALUE', 'Value of Money'), ('OTHER', 'Other')], max_length=20)),
                ('why_us_other', models.TextField(blank=True, null=True)),
                ('about_us', models.CharField(choices=[('ADVERTISING', 'Advertising'), ('EVENT', 'Event'), ('FRIENDS', 'Friend/Family/Colleague'), ('INTERNET', 'Internet Search'), ('MEDIAS', 'Social Media'), ('NEWS', 'News'), ('ALUMNI', 'Alumni'), ('OTHER', 'Other')], max_length=20)),
                ('about_us_other', models.TextField(blank=True, max_length=255, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campus')),
                ('payment_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.addressinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
