# Generated by Django 5.1.1 on 2024-09-12 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="about_us",
            field=models.CharField(
                choices=[
                    ("ADVERTISING", "Advertising"),
                    ("EVENT", "Event"),
                    ("FRIENDS", "Friend/Family/Colleague"),
                    ("INTERNET", "Internet Search"),
                    ("MEDIAS", "Social Media"),
                    ("NEWS", "News"),
                    ("ALUMNI", "Alumni"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_occupation",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_occupation",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="payment_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userauth.addressinfo"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="payment_by",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("PARENT", "Parent/Guardian"),
                    ("COMPANY", "Company"),
                    ("OTHER", "Government/International Agency"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="referred_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="scholarship_details",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="why_us",
            field=models.CharField(
                choices=[
                    ("REPUTATION", "Good brand Reputation"),
                    ("LOCATION", "Location"),
                    ("COURSE", "Course/Mode/Flexibility"),
                    ("VALUE", "Value of Money"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
