# Generated by Django 5.1.1 on 2024-09-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='mother_contact',
            new_name='gurdian_contact',
        ),
    ]
