# Generated by Django 5.1.1 on 2024-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_by',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent/Guardian'), ('COMPANY', 'Company'), ('OTHER', 'Government/International Agency')], max_length=20, null=True),
        ),
    ]
