# Generated by Django 5.1.1 on 2024-09-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_user_alter_student_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='annual_income',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
