# Generated by Django 5.1.1 on 2024-09-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_date_of_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='team_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
