# Generated by Django 5.1.1 on 2024-09-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='about_us',
            field=models.CharField(choices=[('ADVERTISING', 'Advertising'), ('EVENT', 'Event'), ('FRIENDS', 'Friend/Family/Colleague'), ('INTERNET', 'Internet Search'), ('MEDIAS', 'Social Media'), ('NEWS', 'News'), ('ALUMNI', 'Alumni'), ('OTHER', 'Other')], default='FRIENDS', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='annual_income',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='commencing_term',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='why_us',
            field=models.CharField(choices=[('REPUTATION', 'Good brand Reputation'), ('LOCATION', 'Location'), ('COURSE', 'Course/Mode/Flexibility'), ('VALUE', 'Value of Money'), ('OTHER', 'Other')], default='REPUTATION', max_length=20),
        ),
    ]
