# Generated by Django 5.1.1 on 2024-09-15 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_modules_code_remove_modules_program_and_more'),
        ('students', '0002_alter_student_payment_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department'),
        ),
    ]
