# Generated by Django 5.1.1 on 2024-09-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_about_us_alter_student_annual_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='about_us',
            field=models.CharField(blank=True, choices=[('ADVERTISING', 'Advertising'), ('EVENT', 'Event'), ('FRIENDS', 'Friend/Family/Colleague'), ('INTERNET', 'Internet Search'), ('MEDIAS', 'Social Media'), ('NEWS', 'News'), ('ALUMNI', 'Alumni'), ('OTHER', 'Other')], default='FRIENDS', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='members_in_family',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='why_us',
            field=models.CharField(blank=True, choices=[('REPUTATION', 'Good brand Reputation'), ('LOCATION', 'Location'), ('COURSE', 'Course/Mode/Flexibility'), ('VALUE', 'Value of Money'), ('OTHER', 'Other')], default='REPUTATION', max_length=20),
        ),
    ]
