# Generated by Django 5.1.1 on 2024-09-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_user'),
    ]

    operations = [

    ]
