# Generated by Django 5.1.1 on 2024-09-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='personal_info',
        ),
    ]
