# Generated by Django 5.1.1 on 2024-09-22 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_campus_alter_student_department_and_more'),
        ('userauth', '0010_remove_sections_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.sections'),
        ),
    ]
