# Generated by Django 5.1.1 on 2024-09-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
