# Generated by Django 5.1.1 on 2024-09-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='signature',
        ),
    ]
