# Generated by Django 5.1.1 on 2024-09-23 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_student_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
