# Generated by Django 5.1.1 on 2024-09-30 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_student_date_of_admission'),
        ('userauth', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.addressinfo'),
        ),
    ]
