# Generated by Django 5.1.1 on 2024-10-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_student_payment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_due',
            field=models.FloatField(default=0.0),
        ),
    ]
