# Generated by Django 5.1.1 on 2025-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('DAY', 'Day'), ('EVENING', 'Evening')], max_length=50, null=True),
        ),
    ]
