# Generated by Django 5.1.1 on 2025-04-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_student_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
