# Generated by Django 5.1.1 on 2025-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_student_email_sent_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email_sent_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
