# Generated by Django 5.1.1 on 2024-09-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('teacher', '0003_teacher_user'),
        ('userauth', '0012_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.modules')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.sections')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
