# Generated by Django 5.1.1 on 2024-09-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='day',
            new_name='date',
        ),
    ]
