# Generated by Django 5.1.1 on 2024-09-30 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('routine', '0002_rename_day_routine_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.modules')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.program')),
            ],
        ),
    ]
