# Generated by Django 5.1.1 on 2024-09-30 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('routine', '0003_examroutine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examroutine',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examroutine',
            name='program',
        ),
        migrations.RemoveField(
            model_name='examroutine',
            name='start_time',
        ),
        migrations.CreateModel(
            name='ExamProgramRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.program')),
            ],
        ),
        migrations.AddField(
            model_name='examroutine',
            name='routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routine.examprogramroutine'),
            preserve_default=False,
        ),
    ]
