# Generated by Django 5.1.1 on 2024-09-30 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_remove_examroutine_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprogramroutine',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examprogramroutine',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
