# Generated by Django 5.1.1 on 2024-10-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenthistory",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="description",
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="payment_method",
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default=10,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Payments",
        ),
    ]
