# Generated by Django 5.1.1 on 2024-10-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_remove_paymenthistory_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="payment_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
