# Generated by Django 5.1.1 on 2024-10-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymenthistory_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='status',
        ),
    ]
