# Generated by Django 5.1.1 on 2024-10-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_paymenthistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=100),
            preserve_default=False,
        ),
    ]
