# Generated by Django 5.1.1 on 2024-09-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modules",
            name="description",
            field=models.TextField(default="abc"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="modules",
            name="level",
            field=models.CharField(max_length=10),
        ),
    ]
