# Generated by Django 5.1.1 on 2024-09-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="code",
            field=models.TextField(),
        ),
    ]
