# Generated by Django 5.1.1 on 2025-02-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='level',
        ),
        migrations.AlterField(
            model_name='program',
            name='academic_plan',
            field=models.CharField(choices=[('year', 'Year'), ('sem', 'Semester')], default='sem', max_length=20),
        ),
    ]
