# Generated by Django 5.1.1 on 2024-09-06 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_modules_description_alter_modules_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="campus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.campus",
            ),
        ),
    ]
