# Generated by Django 5.1.1 on 2024-09-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_campus_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="code",
            field=models.CharField(max_length=20),
        ),
    ]
