# Generated by Django 5.1.1 on 2024-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_campus_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="campus",
        ),
        migrations.AddField(
            model_name="program",
            name="campus",
            field=models.ManyToManyField(null=True, to="dashboard.campus"),
        ),
    ]
