# Generated by Django 5.1.1 on 2024-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_program_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='level',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='tenure',
            field=models.IntegerField(default=3),
        ),
    ]
