# Generated by Django 5.1.1 on 2025-02-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_modules_level_alter_program_academic_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='level',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='4', max_length=1),
            preserve_default=False,
        ),
    ]
