# Generated by Django 5.1.1 on 2024-09-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_remove_program_campus_program_campus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="campus",
            field=models.ManyToManyField(to="dashboard.campus"),
        ),
    ]
