# Generated by Django 5.1.1 on 2024-09-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_program_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="contact",
            field=models.CharField(),
        ),
    ]
