# Generated by Django 5.1.1 on 2024-09-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0006_remove_department_campus_remove_program_department_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="modules",
            name="code",
            field=models.CharField(max_length=300),
        ),
        migrations.RemoveField(
            model_name="modules",
            name="program",
        ),
        migrations.AddField(
            model_name="modules",
            name="program",
            field=models.ManyToManyField(to="dashboard.program"),
        ),
    ]
