# Generated by Django 5.1.1 on 2025-04-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='code',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
