# Generated by Django 5.1.1 on 2025-04-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_campus_code_alter_modules_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
