# Generated by Django 5.1.1 on 2025-04-24 11:52

from django.db import migrations, models
import uuid

def set_unique_codes(apps, schema_editor):
    import random, string

    def random_code(length=8):
        return ''.join(random.choices(string.ascii_uppercase + string.digits, k=length))

    for model_name in ['Campus', 'Department', 'Modules', 'Program']:
        Model = apps.get_model('dashboard', model_name)
        used_codes = set(Model.objects.values_list('code', flat=True))
        for obj in Model.objects.all():
            if not obj.code or obj.code in used_codes:
                new_code = random_code()
                while new_code in used_codes:
                    new_code = random_code()
                obj.code = new_code
                used_codes.add(new_code)
                obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_campus_code_alter_department_code_and_more'),
    ]

    operations = [
        migrations.RunPython(set_unique_codes),  # Set unique codes first
        migrations.AlterField(
            model_name='campus',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='code',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]