# Generated by Django 5.1.1 on 2024-09-26 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0013_alter_student_date_of_admission"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("Character", "Characher Certificate"),
                            ("Training", "Training Certificate"),
                            ("Academic", "Academic Certificate"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
