# Generated by Django 5.1.1 on 2024-09-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_alter_requestcertificate_certificate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcertificate',
            name='certificate_type',
            field=models.CharField(choices=[('character', 'Characher Certificate'), ('recommendation', 'Recommendation Certificate'), ('training', 'Training Certificate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='requestcertificate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=100),
        ),
    ]
