# Generated by Django 5.1.1 on 2024-10-02 06:19

import django.db.models.deletion
import filehub.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0014_alter_student_payment_address'),
        ('userauth', '0012_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', filehub.fields.ImagePickerField(blank=True, null=True)),
                ('total_marks', models.IntegerField(default=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.sections')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('file', filehub.fields.ImagePickerField(blank=True, null=True)),
                ('marks_obtained', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='Pending', max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
