# Generated by Django 5.1.1 on 2024-10-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignment_description'),
        ('userauth', '0012_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='section',
        ),
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.ManyToManyField(related_name='assignments', to='userauth.sections'),
        ),
    ]
