# Generated by Django 5.1.1 on 2024-10-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmit',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
