# Generated by Django 5.1.1 on 2024-10-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_assignmentsubmit_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmit',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/responses/'),
        ),
    ]
