# Generated by Django 5.1.1 on 2024-10-03 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_alter_assignmentsubmit_file'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='dashboard.modules'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentsubmit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
    ]
