# Generated by Django 5.1.1 on 2024-09-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Father', 'father'), ('Mother', 'mother'), ('Brother', 'brother'), ('Relative', 'relative'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
    ]
