# Generated by Django 5.1.1 on 2024-09-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='date_of_birth_in_ad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
