# Generated by Django 5.1.1 on 2024-09-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_remove_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default='Mr', max_length=255),
            preserve_default=False,
        ),
    ]
