# Generated by Django 5.1.1 on 2024-09-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
    ]
