# Generated by Django 5.1.1 on 2024-09-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_emergencycontact_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='citizenship_img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='citizenship_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
