# Generated by Django 5.1.1 on 2024-09-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_personalinfo_citizenship_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
