# Generated by Django 5.1.1 on 2024-09-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_user_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
