# Generated by Django 5.1.1 on 2024-09-20 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_addressinfo_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='educational_history',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='employment_history',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='english_test',
        ),
        migrations.AddField(
            model_name='educationhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='englishtest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
