# Generated by Django 5.1.1 on 2024-09-20 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('userauth', '0006_remove_personalinfo_educational_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('college', 'College'), ('it', 'IT Support'), ('student_service', 'Student Service Department'), ('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent')], default='student', max_length=100),
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campus')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.program')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
