# Generated by Django 5.1.1 on 2024-09-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_user_role_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Third Semester'), ('4', 'Fourth Semester'), ('5', 'Fifth Semester'), ('6', 'Sixth Semester'), ('7', 'Seventh Semester'), ('8', 'Eighth Semester')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sections',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
