# Generated by Django 5.1.1 on 2024-09-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_alter_addressinfo_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='educational_history',
            field=models.ManyToManyField(blank=True, to='userauth.educationhistory'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='emergency_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.emergencycontact'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='employment_history',
            field=models.ManyToManyField(blank=True, to='userauth.employmenthistory'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='english_test',
            field=models.ManyToManyField(blank=True, to='userauth.englishtest'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='permanent_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='userauth.addressinfo'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='temporary_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_address', to='userauth.addressinfo'),
        ),
    ]
