# Generated by Django 5.1.1 on 2024-09-21 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('userauth', '0008_sections_semester_sections_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.campus'),
        ),
    ]
