# Generated by Django 5.1.1 on 2024-09-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_alter_emergencycontact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishtest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='englishtest',
            name='score',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
