# Generated by Django 5.1.1 on 2024-09-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_remove_sections_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('college', 'College'), ('admission', 'Admission'), ('it', 'IT Support'), ('student_service', 'Student Service Department'), ('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent')], default='student', max_length=100),
        ),
    ]
