# Generated by Django 5.1.1 on 2024-09-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
