# Generated by Django 5.1.1 on 2024-09-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_alter_englishtest_date_alter_englishtest_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishtest',
            name='test',
            field=models.CharField(blank=True, choices=[('TOEFL', 'TOEFL'), ('IELTS', 'IELTS'), ('PTE', 'PTE'), ('CAMBRIDGE', 'Cambridge'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
