# Generated by Django 5.1.1 on 2024-09-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_alter_englishtest_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='english_test',
        ),
    ]
