# Generated by Django 5.1.1 on 2025-02-06 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_syllabus'),
        ('userauth', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='degree_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='institution_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='employer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='englishtest',
            name='score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.program'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='section_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Third Semester'), ('4', 'Fourth Semester'), ('5', 'Fifth Semester'), ('6', 'Sixth Semester'), ('7', 'Seventh Semester'), ('8', 'Eighth Semester')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('college', 'College'), ('admission', 'Admission'), ('it', 'IT Support'), ('student_service', 'Student Service Department'), ('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent')], default='student', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
