# Generated by Django 5.1.1 on 2024-09-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_remove_personalinfo_english_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='english_test',
            field=models.ManyToManyField(blank=True, to='userauth.englishtest'),
        ),
    ]
