# Generated by Django 5.1.1 on 2025-03-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0016_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('college', 'College'), ('admission', 'Admission'), ('it', 'IT Support'), ('student_service', 'Student Service Department'), ('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent')], max_length=100, null=True),
        ),
    ]
