# Generated by Django 5.1.1 on 2025-05-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0017_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='date_of_birth_in_bs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
