# Generated by Django 5.1.1 on 2025-05-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0018_personalinfo_date_of_birth_in_bs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='date_of_birth_in_bs',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
